package com.lisovskyi.core_service.case_event;

import com.lisovskyi.core_service.case_event.dto.request.CaseEventAutoRegisterRequest;
import com.lisovskyi.core_service.case_event.dto.request.CaseEventManualRegisterRequest;
import com.lisovskyi.core_service.case_event.dto.request.CaseEventOccurredAtChangeRequest;
import com.lisovskyi.core_service.case_event.dto.request.CaseEventUpdateRequest;
import com.lisovskyi.core_service.case_event.dto.response.CaseEventResponse;
import com.lisovskyi.core_service.case_event.enums.EventCode;
import com.sentio.shared.dto.PageResponse;
import com.sentio.shared.entity.id.case_.CaseId;
import com.sentio.shared.entity.id.case_event.CaseEventId;
import com.sentio.shared.entity.id.organization.OrganizationId;
import com.sentio.shared.entity.id.user.UserId;
import com.sentio.shared.security.CurrentOrganizationId;
import com.sentio.shared.security.CurrentUserId;
import com.sentio.shared.web.LocationUtility;
import jakarta.validation.Valid;
import java.net.URI;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Pageable;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/cases/{caseId}/case-events")
@RequiredArgsConstructor
public class CaseEventController {

    private final CaseEventService caseEventService;

    @GetMapping
    public ResponseEntity<PageResponse<CaseEventResponse>> getAllCaseEvents(
            @PathVariable CaseId caseId,
            @CurrentOrganizationId OrganizationId organizationId,
            @RequestParam(required = false) EventCode eventCode,
            final Pageable pageable) {
        return ResponseEntity.ok(caseEventService.getAllCaseEvents(caseId, organizationId, eventCode, pageable));
    }

    @GetMapping("/{eventId}")
    public ResponseEntity<CaseEventResponse> getCaseEventById(
            @PathVariable CaseEventId eventId,
            @PathVariable CaseId caseId,
            @CurrentOrganizationId OrganizationId organizationId) {
        return ResponseEntity.ok(caseEventService.getCaseEventById(caseId, eventId, organizationId));
    }

    // вручну створювати подію
    @PostMapping("/manual")
    public ResponseEntity<CaseEventResponse> registerCaseEvent(
            @PathVariable CaseId caseId,
            @CurrentOrganizationId OrganizationId organizationId,
            @CurrentUserId UserId createdById,
            @RequestBody @Valid CaseEventManualRegisterRequest request) {
        CaseEventResponse response = caseEventService.registerCaseEvent(caseId, organizationId, createdById, request);
        URI location = LocationUtility.buildLocation(response.id());

        return ResponseEntity.created(location).body(response);
    }

    // автоматично через Go сервіс
    @PostMapping("/autogenerated")
    @PreAuthorize("hasRole('SERVICE')")
    public ResponseEntity<CaseEventResponse> registerCaseEvent(
            @PathVariable CaseId caseId,
            @CurrentOrganizationId OrganizationId organizationId,
            @RequestBody @Valid CaseEventAutoRegisterRequest request) {
        CaseEventResponse response = caseEventService.registerRegistryCaseEvent(caseId, organizationId, request);
        URI location = LocationUtility.buildLocation(response.id());

        return ResponseEntity.created(location).body(response);
    }

    @PatchMapping("/{eventId}/occurred-at")
    @PreAuthorize("hasAnyRole('OWNER', 'LAWYER')")
    public ResponseEntity<CaseEventResponse> changeOccurredAt(
            @PathVariable CaseId caseId,
            @PathVariable CaseEventId eventId,
            @CurrentOrganizationId OrganizationId organizationId,
            @CurrentUserId UserId changedById,
            @RequestBody @Valid CaseEventOccurredAtChangeRequest request) {
        CaseEventResponse response =
                caseEventService.changeOccurredAt(caseId, eventId, organizationId, changedById, request);
        return ResponseEntity.ok(response);
    }

    @PatchMapping("/{eventId}")
    public ResponseEntity<CaseEventResponse> updateCaseEvent(
            @PathVariable CaseId caseId,
            @PathVariable CaseEventId eventId,
            @CurrentOrganizationId OrganizationId organizationId,
            @RequestBody @Valid CaseEventUpdateRequest request) {
        return ResponseEntity.ok(caseEventService.updateCaseEvent(caseId, eventId, organizationId, request));
    }

    @DeleteMapping("/{eventId}")
    @PreAuthorize("hasAnyRole('OWNER', 'LAWYER')")
    public ResponseEntity<Void> deleteCaseEvent(
            @PathVariable CaseId caseId,
            @PathVariable CaseEventId eventId,
            @CurrentOrganizationId OrganizationId organizationId,
            @CurrentUserId UserId deletedById,
            @RequestParam(required = false) String deleteReason) {
        caseEventService.deleteCaseEvent(caseId, eventId, organizationId, deletedById, deleteReason);
        return ResponseEntity.noContent().build();
    }

    @PostMapping("/{eventId}/restore")
    @PreAuthorize("hasAnyRole('OWNER', 'LAWYER')")
    public ResponseEntity<Void> restoreCaseEvent(
            @PathVariable CaseId caseId,
            @PathVariable CaseEventId eventId,
            @CurrentOrganizationId OrganizationId organizationId,
            @CurrentUserId UserId restoredById) {
        caseEventService.restoreCaseEvent(caseId, eventId, organizationId, restoredById);
        return ResponseEntity.noContent().build();
    }
}
