package com.lisovskyi.core_service.case_event;

import com.lisovskyi.core_service.case_event.dto.request.CaseEventAutoRegisterRequest;
import com.lisovskyi.core_service.case_event.dto.request.CaseEventManualRegisterRequest;
import com.lisovskyi.core_service.case_event.dto.response.CaseEventResponse;
import com.sentio.shared.security.CurrentOrganizationId;
import com.sentio.shared.security.CurrentUserId;
import com.sentio.shared.web.LocationUtility;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;

import java.net.URI;

@RestController
@RequestMapping("/cases/{caseId}/case-events")
@RequiredArgsConstructor
public class CaseEventController {

    private final CaseEventService caseEventService;

    // вручну створювати подію
    @PostMapping("/manual")
    public ResponseEntity<CaseEventResponse> registerCaseEvent(
            @PathVariable Long caseId,
            @CurrentOrganizationId Long organizationId,
            @CurrentUserId Long createdById,
            @RequestBody @Valid CaseEventManualRegisterRequest request) {
        CaseEventResponse response = caseEventService.registerCaseEvent(caseId, organizationId, createdById, request);
        URI location = LocationUtility.buildLocation(response.id());

        return ResponseEntity.created(location).body(response);
    }

    // автоматично через Go сервіс
    @PostMapping("/autogenerated")
    @PreAuthorize("hasRole('SERVICE')")
    public ResponseEntity<CaseEventResponse> registerCaseEvent(
            @PathVariable Long caseId,
            @CurrentOrganizationId Long organizationId,
            @RequestBody @Valid CaseEventAutoRegisterRequest request) {
        CaseEventResponse response = caseEventService.registerRegistryCaseEvent(caseId, organizationId, request);
        URI location = LocationUtility.buildLocation(response.id());

        return ResponseEntity.created(location).body(response);
    }
}
